# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-06 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='用户名称')),
                ('password', models.CharField(max_length=50, verbose_name='用户密码')),
                ('age', models.IntegerField(default=18, verbose_name='用户年龄')),
                ('nickname', models.CharField(max_length=255, verbose_name='用户昵称')),
                ('birthday', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
